services:
  app: #TODO find suitable name
    build: .
    ports:
      - "${REST_PORT}:${REST_PORT}"
      - "${MQTT_PORT}:${MQTT_PORT}"
    environment:
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - REST_PORT=${REST_PORT}
      - REST_HOST=${REST_HOST}
      - MQTT_PORT=${MQTT_PORT}
      - MQTT_HOST=${MQTT_HOST}
    depends_on:
      - db

  db:
    image: mongo:latest
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: